version: "2"

services:
  canary_cousin:
    build:
      context: ./canary_cousin
      dockerfile: ./Dockerfile
    ports:
      - "12306:8000"

  fbi:
    build:
      context: ./fbi
      dockerfile: ./Dockerfile
    ports:
      - "12307:8000"

  stage:
    build:
      context: ./stage
      dockerfile: ./Dockerfile
    ports:
      - "12308:8000"

  cdc:
    build:
      context: ./cdc
      dockerfile: ./Dockerfile
    ports:
      - "12311:8000"